services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root1
      - POSTGRES_DB=jwt_security
    volumes:
      - C:\dataa:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    restart: always
  app:
    build:
      context: .
    container_name: app
    depends_on:
        - db
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root1
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jwt_security
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=root1
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    image: apires
    ports:
      - "8080:8080"




